### ISSUE TITLE
Unable to download submssions

### ISSUE THREAD

**Issue by parth-io** [Nullifiers/Hackerrank-Solution-Crawler#48]
**Description**
When downloading my submissions it returns the JSONDecodeError (see the code below).
The error is traced to the method `login(username, password)` in line 45 of crawler.py.
As far I can figure out, the value of `data` for  `data = resp.json()` is empty, resp.json() does not return anything.

***Steps taken to try to fix***
I could not figure out why `resp.json()` returns nothing, so I tried writing my own crawler based on yours to simplify and understand what's going on.
My crawler worked fine enough in providing the authentication details and in getting the models or all the submissions, but when it came to calling resp.json() for each challenge in the `get_submission(self, submissions)` method, it failed and retured the same JSONDecodeError.

If you wish, I can email my modified crawler to you.

**Desktop:**
 - Kubuntu
- pip 20.0.2
- Python 3.8

**Error message**
```
user@pc:~$ hsc
Hackerrank Username: user@email.com
Hackerrank Password: 
Traceback (most recent call last):
  File "/home/parth/.local/bin/hsc", line 8, in <module>
    sys.exit(main())
  File "/home/parth/.local/lib/python3.8/site-packages/hsc/crawler.py", line 224, in main
    if not crawler.authenticate():
  File "/home/parth/.local/lib/python3.8/site-packages/hsc/crawler.py", line 65, in authenticate
    return self.login(username, password)
  File "/home/parth/.local/lib/python3.8/site-packages/hsc/crawler.py", line 45, in login
    data = resp.json()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by rishabhsingh971** [comment]
Does this error occur everytime you run the script?

**Comment by Eunoia1729** [comment]
> Does this error occur everytime you run the script?

yes. Is this project no more active ?

**Comment by rajat19** [comment]
@parth-io @Eunoia1729 sorry for delay in response
I have updated the login url for hackerrank which caused issue.
